"""Backward-compatible imports for the former dashboard options module.

Domain code now lives under :mod:`lambdaclass.options`.
"""

from lambdaclass.options import (
    PRESETS,
    Leg,
    ParamSpec,
    PresetFactory,
    PresetSpec,
    Side,
    black_scholes_price,
    build_preset_legs,
    find_breakevens,
    greeks,
    intrinsic_value,
    leg_from_row,
    legs_from_dataframe,
    legs_to_dataframe,
    parse_option_date,
    position_pnl,
    preset_butterfly,
    preset_iron_butterfly,
    preset_iron_condor,
    preset_long_call,
    preset_long_put,
    preset_ratio_spread,
    preset_short_call,
    preset_short_put,
    preset_straddle,
    preset_strangle,
    preset_vertical_spread,
    safe_option_mid,
    snap_to_chain,
    years_between,
)

__all__ = [
    "PRESETS",
    "Leg",
    "ParamSpec",
    "PresetFactory",
    "PresetSpec",
    "Side",
    "black_scholes_price",
    "build_preset_legs",
    "find_breakevens",
    "greeks",
    "intrinsic_value",
    "leg_from_row",
    "legs_from_dataframe",
    "legs_to_dataframe",
    "parse_option_date",
    "position_pnl",
    "preset_butterfly",
    "preset_iron_butterfly",
    "preset_iron_condor",
    "preset_long_call",
    "preset_long_put",
    "preset_ratio_spread",
    "preset_short_call",
    "preset_short_put",
    "preset_straddle",
    "preset_strangle",
    "preset_vertical_spread",
    "safe_option_mid",
    "snap_to_chain",
    "years_between",
]
